controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

joint_state_broadcaster:
  ros__parameters:
    extra_joints: ["RIGHT_FRONT_WHEEL_JOINT", "LEFT_FRONT_WHEEL_JOINT"]

ackermann_steering_controller:
  ros__parameters:

    reference_timeout: 0.1
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true
    rear_wheels_names: [RIGHT_REAR_WHEEL_JOINT, LEFT_REAR_WHEEL_JOINT]
    front_wheels_names: [RIGHT_HINGE_JOINT, LEFT_HINGE_JOINT]

    wheelbase: 0.324
    front_wheel_track: 0.387
    rear_wheel_track: 0.387
    front_wheels_radius: 0.055
    rear_wheels_radius: 0.055

    steering:
      min_position: -0.5236
      max_position: 0.5236

      max_velocity: 1.0
